In [16]:
import pandas as pd

In [17]:
df = pd.read_csv("성적 예측 분석 데이터 수집 설문조사.csv")
df.head()

,타임스탬프,학년,19-1 전과목 중간고사 성적 평균,"국어 (국어, 문학, 고전)","영어(영어, 영어 I, 심화 영어 독해 I)","수학(수학, 수학 I, 수학연습 I, 수학연습 II, 확률과 통계, 기하와 벡터)",통합 과학,한문 I,한국지리,윤리와 사상,...,하루에 스마트폰을 평균 몇 시간 사용하시나요?,스마트폰을 주로 어떤 용도로 사용하시나요?,방과 후 학습 장소는 주로 어디입니까?,"현재 사교육을 받고 있습니까? (과외나 인터넷 강의 포함 단, EBS 인터넷 강의 제외)",현재 받고 있는 사교육의 개수를 입력해주세요.,현재 받고 있는 사교육의 형태를 선택해주세요.,하루 평균 수면 시간은 어느 정도입니까?,하루에 운동을 평균 몇 시간 하나요?,어떤 형태의 운동을 주로 하나요?,평소에 아침식사를 하나요?
0,2019/05/17 10:57:50 오전 GMT+9,2학년 자연,92.26,95.0,100.0,77.4,NaN,NaN,NaN,NaN,...,3시간 이상 5시간 미만,"문자 메시지 및 메신저 (카카오톡, 라인 등);SNS (페이스북, 인스타그램, 트위...",학교 (야간자율학습),있다,3.0,학원;인터넷 강의 (EBS 제외),6.0,10분 이상 30분 미만,가벼운 산책 (식후 운동장 걷기 등),매일 아침식사를 한다
1,2019/05/17 11:05:25 오전 GMT+9,2학년 자연,78.00,85.0,70.0,65.0,NaN,40.0,NaN,NaN,...,3시간 이상 5시간 미만,"문자 메시지 및 메신저 (카카오톡, 라인 등);SNS (페이스북, 인스타그램, 트위...",집,있다,4.0,학원;인터넷 강의 (EBS 제외),6.0,10분 이상 30분 미만,근력운동,매일 아침식사를 한다
2,2019/05/17 2:30:49 오후 GMT+9,2학년 자연,64.20,94.0,57.3,62.6,NaN,21.4,NaN,NaN,...,5시간 이상 7시간 미만,"문자 메시지 및 메신저 (카카오톡, 라인 등);SNS (페이스북, 인스타그램, 트위...",학원 (수업 및 자습),있다,6.0,"학원;과외 (개인, 그룹 등);인터넷 강의 (EBS 제외)",6.0,10분 이상 30분 미만,가벼운 산책 (식후 운동장 걷기 등),매일 아침식사를 한다
3,2019/05/17 2:31:38 오후 GMT+9,2학년 자연,75.68,91.6,83.2,74.0,NaN,75.1,NaN,NaN,...,1시간 이상 3시간 미만,"음악감상;콘텐츠 관람 (유투브, 웹툰, 넷플릭스 등)",학원 (수업 및 자습),있다,3.0,학원,6.0,10분 이상 30분 미만,가벼운 산책 (식후 운동장 걷기 등),매일 아침식사를 한다
4,2019/05/19 4:18:08 오전 GMT+9,2학년 자연,80.53,87.6,54.9,97.0,NaN,89.1,NaN,NaN,...,3시간 이상 5시간 미만,"문자 메시지 및 메신저 (카카오톡, 라인 등);음악감상;콘텐츠 관람 (유투브, 웹툰...",학원 (수업 및 자습),있다,5.0,학원;인터넷 강의 (EBS 제외),7.0,10분 미만,가벼운 산책 (식후 운동장 걷기 등),매일 아침식사를 한다

In [18]:
df.columns

Index(['타임스탬프', '학년', '19-1 전과목 중간고사 성적 평균', '국어 (국어, 문학, 고전)',
       '영어(영어, 영어 I, 심화 영어 독해 I)',
       '수학(수학, 수학 I, 수학연습 I, 수학연습 II, 확률과 통계, 기하와 벡터)', '통합 과학', '한문 I',
       '한국지리', '윤리와 사상', '물리학 I', '화학 I', '생명과학 I', '지구과학 I', '사회문화', '동아시아사',
       '생활과 윤리', '과학', '과학 II(물리학 II, 화학 II, 생명과학 II, 지구과학II)',
       '일주일에 TV를 며칠 시청하시나요?', '1회 평균 TV 시청 시간은 몇 시간인가요?',
       'TV를 시청하실 때 주로 어떤 장르의 프로그램을 시청하시나요?', '본인은 현재 스마트폰을 소유하고 있나요?',
       '하루에 스마트폰을 평균 몇 시간 사용하시나요?', '스마트폰을 주로 어떤 용도로 사용하시나요?',
       '방과 후 학습 장소는 주로 어디입니까?',
       '현재 사교육을 받고 있습니까?  (과외나 인터넷 강의 포함 단, EBS 인터넷 강의 제외)',
       '현재 받고 있는 사교육의 개수를 입력해주세요. ', '현재 받고 있는 사교육의 형태를 선택해주세요.',
       '하루 평균 수면 시간은 어느 정도입니까?', '하루에 운동을 평균 몇 시간 하나요?', '어떤 형태의 운동을 주로 하나요?',
       '평소에 아침식사를 하나요?'],
      dtype='object')

In [19]:
score = df[['영어(영어, 영어 I, 심화 영어 독해 I)', 
          '수학(수학, 수학 I, 수학연습 I, 수학연습 II, 확률과 통계, 기하와 벡터)',
         '국어 (국어, 문학, 고전)', '19-1 전과목 중간고사 성적 평균']]

In [20]:
score

,"영어(영어, 영어 I, 심화 영어 독해 I)","수학(수학, 수학 I, 수학연습 I, 수학연습 II, 확률과 통계, 기하와 벡터)","국어 (국어, 문학, 고전)",19-1 전과목 중간고사 성적 평균
0,100.0,77.40,95.0,92.2600
1,70.0,65.00,85.0,78.0000
2,57.3,62.60,94.0,64.2000
3,83.2,74.00,91.6,75.6800
4,54.9,97.00,87.6,80.5300
5,60.0,80.00,60.0,70.0000
6,54.4,95.00,81.2,78.3000
7,91.7,96.00,96.8,93.0800
8,94.0,90.00,91.0,89.7800
9,66.0,91.00,82.0,78.2400
10,64.5,94.00,92.0,79.6100
11,62.0,70.00,88.0,62.0000
12,47.6,56.80,90.6,65.8600
13,71.6,85.40,88.6,87.4400
14,56.0,68.00,95.0,3.5000
15,81.7,87.20,91.0,90.0000
16,84.0,74.00,85.0,2.9200
17,60.9,82.00,88.6,3.8400
18,47.0,54.00,64.5,52.0000
19,47.0,54.00,64.5,52.0000
20,46.0,59.00,70.0,59.2000
21,64.0,68.00,76.0,67.0000
22,64.3,89.70,84.5,80.0200
23,78.0,82.00,91.0,88.0000
24,53.0,83.00,61.0,68.7500
25,44.0,21.00,81.0,65.0000
26,76.0,78.33,97.0,2.4000
27,81.9,78.00,93.6,3.0300
28,57.0,75.00,90.0,4.5000
29,72.6,51.30,82.5,71.6500
...,...,...,...,...
54,75.6,89.00,87.8,83.6400
55,37.0,55.00,86.0,66.1400
56,76.2,76.50,90.5,82.5500
57,81.0,77.00,94.0,3.2800
58,48.0,57.00,79.0,70.6600
59,86.3,94.30,91.0,90.5700
60,79.0,78.00,81.0,82.0000
61,48.0,55.00,72.0,62.5000
62,72.2,80.30,86.0,84.0000
63,61.0,85.00,91.0,83.2600
64,60.0,76.00,81.0,72.7500
65,60.0,67.00,60.0,55.5000
66,73.6,79.00,93.5,84.1300
67,34.2,16.60,66.0,42.0000
68,76.0,80.00,83.0,5.0000
69,64.0,60.00,91.0,66.2800
70,74.0,67.00,65.0,74.5500
71,55.4,84.00,90.8,84.3200
72,85.0,66.00,82.0,82.0000
73,64.0,58.00,85.0,71.0000
74,65.3,73.10,92.0,76.9200
75,79.6,93.10,81.5,83.4254
76,79.6,93.10,81.5,83.4254
77,79.6,93.10,81.5,83.4254
78,72.0,71.33,80.0,75.0000
79,50.0,78.00,90.0,3.2000
80,80.8,73.80,96.9,2.4200
81,76.0,84.00,100.0,2.5000
82,77.0,97.00,96.8,94.4800
83,84.0,83.00,80.0,82.0000

In [21]:
colums_name = ['math', "english", 'korean', 'average']

In [24]:
score.columns = colums_name

In [26]:
score.head()

    math  english  korean  average
0  100.0     77.4    95.0    92.26
1   70.0     65.0    85.0    78.00
2   57.3     62.6    94.0    64.20
3   83.2     74.0    91.6    75.68
4   54.9     97.0    87.6    80.53

## average 는 전과목 평균 / 3과목 평균을 구해서 추가

#### 평균 = (수학+영어+국어)/3

In [34]:
math = score.math

In [35]:
type(math)

pandas.core.series.Series

In [36]:
english = score.english

In [39]:
korean = score.korean

In [42]:
total = math + english + korean
total

0     272.40
1     220.00
2     213.90
3     248.80
4     239.50
5     200.00
6     230.60
7     284.50
8     275.00
9     239.00
10    250.50
11    220.00
12    195.00
13    245.60
14    219.00
15    259.90
16    243.00
17    231.50
18    165.50
19    165.50
20    175.00
21    208.00
22    238.50
23    251.00
24    197.00
25    146.00
26    251.33
27    253.50
28    222.00
29    206.40
       ...
54    252.40
55    178.00
56    243.20
57    252.00
58    184.00
59    271.60
60    238.00
61    175.00
62    238.50
63    237.00
64    217.00
65    187.00
66    246.10
67    116.80
68    239.00
69    215.00
70    206.00
71    230.20
72    233.00
73    207.00
74    230.40
75    254.20
76    254.20
77    254.20
78    223.33
79    218.00
80    251.50
81    260.00
82    270.80
83    247.00
Length: 84, dtype: float64

In [44]:
average_3 = total/3
average_3

0     90.800000
1     73.333333
2     71.300000
3     82.933333
4     79.833333
5     66.666667
6     76.866667
7     94.833333
8     91.666667
9     79.666667
10    83.500000
11    73.333333
12    65.000000
13    81.866667
14    73.000000
15    86.633333
16    81.000000
17    77.166667
18    55.166667
19    55.166667
20    58.333333
21    69.333333
22    79.500000
23    83.666667
24    65.666667
25    48.666667
26    83.776667
27    84.500000
28    74.000000
29    68.800000
        ...
54    84.133333
55    59.333333
56    81.066667
57    84.000000
58    61.333333
59    90.533333
60    79.333333
61    58.333333
62    79.500000
63    79.000000
64    72.333333
65    62.333333
66    82.033333
67    38.933333
68    79.666667
69    71.666667
70    68.666667
71    76.733333
72    77.666667
73    69.000000
74    76.800000
75    84.733333
76    84.733333
77    84.733333
78    74.443333
79    72.666667
80    83.833333
81    86.666667
82    90.266667
83    82.333333
Length: 84, dtype: float64

In [47]:
score['average_3'] = average_3

c:\users\jangy\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [48]:
score

     math  english  korean  average  average_3
0   100.0    77.40    95.0  92.2600  90.800000
1    70.0    65.00    85.0  78.0000  73.333333
2    57.3    62.60    94.0  64.2000  71.300000
3    83.2    74.00    91.6  75.6800  82.933333
4    54.9    97.00    87.6  80.5300  79.833333
5    60.0    80.00    60.0  70.0000  66.666667
6    54.4    95.00    81.2  78.3000  76.866667
7    91.7    96.00    96.8  93.0800  94.833333
8    94.0    90.00    91.0  89.7800  91.666667
9    66.0    91.00    82.0  78.2400  79.666667
10   64.5    94.00    92.0  79.6100  83.500000
11   62.0    70.00    88.0  62.0000  73.333333
12   47.6    56.80    90.6  65.8600  65.000000
13   71.6    85.40    88.6  87.4400  81.866667
14   56.0    68.00    95.0   3.5000  73.000000
15   81.7    87.20    91.0  90.0000  86.633333
16   84.0    74.00    85.0   2.9200  81.000000
17   60.9    82.00    88.6   3.8400  77.166667
18   47.0    54.00    64.5  52.0000  55.166667
19   47.0    54.00    64.5  52.0000  55.166667
20   46.0    59.00    70.0  59.2000  58.333333
21   64.0    68.00    76.0  67.0000  69.333333
22   64.3    89.70    84.5  80.0200  79.500000
23   78.0    82.00    91.0  88.0000  83.666667
24   53.0    83.00    61.0  68.7500  65.666667
25   44.0    21.00    81.0  65.0000  48.666667
26   76.0    78.33    97.0   2.4000  83.776667
27   81.9    78.00    93.6   3.0300  84.500000
28   57.0    75.00    90.0   4.5000  74.000000
29   72.6    51.30    82.5  71.6500  68.800000
..    ...      ...     ...      ...        ...
54   75.6    89.00    87.8  83.6400  84.133333
55   37.0    55.00    86.0  66.1400  59.333333
56   76.2    76.50    90.5  82.5500  81.066667
57   81.0    77.00    94.0   3.2800  84.000000
58   48.0    57.00    79.0  70.6600  61.333333
59   86.3    94.30    91.0  90.5700  90.533333
60   79.0    78.00    81.0  82.0000  79.333333
61   48.0    55.00    72.0  62.5000  58.333333
62   72.2    80.30    86.0  84.0000  79.500000
63   61.0    85.00    91.0  83.2600  79.000000
64   60.0    76.00    81.0  72.7500  72.333333
65   60.0    67.00    60.0  55.5000  62.333333
66   73.6    79.00    93.5  84.1300  82.033333
67   34.2    16.60    66.0  42.0000  38.933333
68   76.0    80.00    83.0   5.0000  79.666667
69   64.0    60.00    91.0  66.2800  71.666667
70   74.0    67.00    65.0  74.5500  68.666667
71   55.4    84.00    90.8  84.3200  76.733333
72   85.0    66.00    82.0  82.0000  77.666667
73   64.0    58.00    85.0  71.0000  69.000000
74   65.3    73.10    92.0  76.9200  76.800000
75   79.6    93.10    81.5  83.4254  84.733333
76   79.6    93.10    81.5  83.4254  84.733333
77   79.6    93.10    81.5  83.4254  84.733333
78   72.0    71.33    80.0  75.0000  74.443333
79   50.0    78.00    90.0   3.2000  72.666667
80   80.8    73.80    96.9   2.4200  83.833333
81   76.0    84.00   100.0   2.5000  86.666667
82   77.0    97.00    96.8  94.4800  90.266667
83   84.0    83.00    80.0  82.0000  82.333333

[84 rows x 5 columns]

In [53]:
score['avg_gap'] = score['average'] - score['average_3']

c:\users\jangy\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [54]:
score

     math  english  korean  average  average_3    avg_gap
0   100.0    77.40    95.0  92.2600  90.800000   1.460000
1    70.0    65.00    85.0  78.0000  73.333333   4.666667
2    57.3    62.60    94.0  64.2000  71.300000  -7.100000
3    83.2    74.00    91.6  75.6800  82.933333  -7.253333
4    54.9    97.00    87.6  80.5300  79.833333   0.696667
5    60.0    80.00    60.0  70.0000  66.666667   3.333333
6    54.4    95.00    81.2  78.3000  76.866667   1.433333
7    91.7    96.00    96.8  93.0800  94.833333  -1.753333
8    94.0    90.00    91.0  89.7800  91.666667  -1.886667
9    66.0    91.00    82.0  78.2400  79.666667  -1.426667
10   64.5    94.00    92.0  79.6100  83.500000  -3.890000
11   62.0    70.00    88.0  62.0000  73.333333 -11.333333
12   47.6    56.80    90.6  65.8600  65.000000   0.860000
13   71.6    85.40    88.6  87.4400  81.866667   5.573333
14   56.0    68.00    95.0   3.5000  73.000000 -69.500000
15   81.7    87.20    91.0  90.0000  86.633333   3.366667
16   84.0    74.00    85.0   2.9200  81.000000 -78.080000
17   60.9    82.00    88.6   3.8400  77.166667 -73.326667
18   47.0    54.00    64.5  52.0000  55.166667  -3.166667
19   47.0    54.00    64.5  52.0000  55.166667  -3.166667
20   46.0    59.00    70.0  59.2000  58.333333   0.866667
21   64.0    68.00    76.0  67.0000  69.333333  -2.333333
22   64.3    89.70    84.5  80.0200  79.500000   0.520000
23   78.0    82.00    91.0  88.0000  83.666667   4.333333
24   53.0    83.00    61.0  68.7500  65.666667   3.083333
25   44.0    21.00    81.0  65.0000  48.666667  16.333333
26   76.0    78.33    97.0   2.4000  83.776667 -81.376667
27   81.9    78.00    93.6   3.0300  84.500000 -81.470000
28   57.0    75.00    90.0   4.5000  74.000000 -69.500000
29   72.6    51.30    82.5  71.6500  68.800000   2.850000
..    ...      ...     ...      ...        ...        ...
54   75.6    89.00    87.8  83.6400  84.133333  -0.493333
55   37.0    55.00    86.0  66.1400  59.333333   6.806667
56   76.2    76.50    90.5  82.5500  81.066667   1.483333
57   81.0    77.00    94.0   3.2800  84.000000 -80.720000
58   48.0    57.00    79.0  70.6600  61.333333   9.326667
59   86.3    94.30    91.0  90.5700  90.533333   0.036667
60   79.0    78.00    81.0  82.0000  79.333333   2.666667
61   48.0    55.00    72.0  62.5000  58.333333   4.166667
62   72.2    80.30    86.0  84.0000  79.500000   4.500000
63   61.0    85.00    91.0  83.2600  79.000000   4.260000
64   60.0    76.00    81.0  72.7500  72.333333   0.416667
65   60.0    67.00    60.0  55.5000  62.333333  -6.833333
66   73.6    79.00    93.5  84.1300  82.033333   2.096667
67   34.2    16.60    66.0  42.0000  38.933333   3.066667
68   76.0    80.00    83.0   5.0000  79.666667 -74.666667
69   64.0    60.00    91.0  66.2800  71.666667  -5.386667
70   74.0    67.00    65.0  74.5500  68.666667   5.883333
71   55.4    84.00    90.8  84.3200  76.733333   7.586667
72   85.0    66.00    82.0  82.0000  77.666667   4.333333
73   64.0    58.00    85.0  71.0000  69.000000   2.000000
74   65.3    73.10    92.0  76.9200  76.800000   0.120000
75   79.6    93.10    81.5  83.4254  84.733333  -1.307933
76   79.6    93.10    81.5  83.4254  84.733333  -1.307933
77   79.6    93.10    81.5  83.4254  84.733333  -1.307933
78   72.0    71.33    80.0  75.0000  74.443333   0.556667
79   50.0    78.00    90.0   3.2000  72.666667 -69.466667
80   80.8    73.80    96.9   2.4200  83.833333 -81.413333
81   76.0    84.00   100.0   2.5000  86.666667 -84.166667
82   77.0    97.00    96.8  94.4800  90.266667   4.213333
83   84.0    83.00    80.0  82.0000  82.333333  -0.333333

[84 rows x 6 columns]